/**
 * config.js
 *
 * Auto-generated by scripts/deploy.js every time you deploy.
 * Do not hand-edit this file — it gets overwritten on the next deploy.
 *
 * Last deploy: 2026-08-08T08:05:01.681Z
 */
const CONTRACT_ADDRESS = "0x65d00Ecc7978393fE8A237659EBa96e1BE981Aa7";
const CONTRACT_NETWORK = "sepolia";
