/**
 * config.js
 *
 * Auto-generated by scripts/deploy.js every time you deploy.
 * Do not hand-edit this file - it gets overwritten on the next deploy.
 *
 * Last deploy: 2026-08-12T03:59:01.441Z
 */
const CONTRACT_ADDRESS = "0x3fc006d66Ad33d91900252e5cFD787771dcD48fA";
const CONTRACT_NETWORK = "sepolia";
