/**
 * config.js
 *
 * Auto-generated by scripts/deploy.js every time you deploy.
 * Do not hand-edit this file - it gets overwritten on the next deploy.
 *
 * Last deploy: 2026-08-12T01:29:24.746Z
 */
const CONTRACT_ADDRESS = "0x5Cb749289b5642EB3A10F401c7fA0438323fbB0F";
const CONTRACT_NETWORK = "sepolia";
